# Generated by Django 3.1.6 on 2021-02-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0002_auto_20210228_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default='2021-02-28'),
        ),
    ]
