# Generated by Django 3.1.6 on 2021-03-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0003_auto_20210228_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items_ordered',
            field=models.ManyToManyField(help_text='To select multiple hold ctrl and then select', to='internal.Dish'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default='2021-03-01'),
        ),
    ]
