# Generated by Django 3.1.6 on 2021-03-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0004_auto_20210301_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity_type',
            field=models.TextField(choices=[('kg', 'Kilogram'), ('lt', 'Litre'), ('no.', '')], default='_'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_by',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
